### ISSUE TITLE
Unable to use expand or tabs with mermaid

### ISSUE THREAD

**Issue by ChrisSidebotham** [thegeeklab/hugo-geekdoc#741] opened 2023-11-07 14:41 UTC
# Description

When using mermaid, if you choose to embed mermaid content within a expand container - the mermaid will fail to render with a syntax error. When trying to use tabs only the first diagram is generated.

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/48600046/4a305634-1f59-41e2-8b92-db49847f0c39)
![image](https://github.com/thegeeklab/hugo-geekdoc/assets/48600046/bde74263-4362-4578-87d1-702cca54d81b)

**Comment by xoxys** [comment] 2023-11-07 15:13
Thanks for your report. Unfortunately, I'm not able to reproduce it for expands. Can you please provide a reproducible example? There are some smaller rendering issues while using it in tabs, but I'm also not able to reproduce the error from your screenshot. 

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/3391958/4c5f548a-6732-4267-b484-09264e8f1140)

**Comment by ChrisSidebotham** [comment] 2023-11-07 16:16
{{< expand "GitFlow Diagram">}}
  {{< mermaid class="text-center" >}}
    %%{init: { 'logLevel': 'debug', 'gitGraph': {'rotateCommitLabel': false}} }%%
    gitGraph LR:
        commit id:"Fork Repo"
        branch anchor
        checkout anchor
        commit id:"Sync Upstream/main" type: HIGHLIGHT
        branch avm-type-provider-resource-workflow
        checkout avm-type-provider-resource-workflow
        commit id:"Add Workflow File for Resource/Pattern"
        branch avm-type-provider-resource
        checkout main
        merge avm-type-provider-resource-workflow id: "merge workflow for GitHub Actions Testing" type: HIGHLIGHT
        checkout avm-type-provider-resource
        commit id:"Init"
        commit id:"Patch 1"
        commit id:"Patch 2"
        checkout main
        merge avm-type-provider-resource
  {{< /mermaid >}}
{{< /expand >}}

**Comment by xoxys** [comment] 2023-11-07 20:19
Works here. Maybe check your theme and hugo version.

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/3391958/aa67dd59-f265-477d-8fa5-40b634b4159e)

**Comment by ChrisSidebotham** [comment] 2023-11-13 11:25
Having checked the git version - Expansion now works however Tabs does not the 2nd tab does not render

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/48600046/bbc4d0a5-ef3a-4254-8857-b5e9a512816e)

![image](https://github.com/thegeeklab/hugo-geekdoc/assets/48600046/acc2070b-0440-4aa6-9dc5-1c3221cf6758)

**Comment by xoxys** [comment] 2023-11-17 13:53
Ref: https://github.com/mermaid-js/mermaid/issues/1846
We might be able to implement a similar workaround like https://github.com/McShelby/hugo-theme-relearn/issues/187 however, this should be fixed upstream, and it's a bit of paint that every user needs to implement a fix on its own.

**Closed** 2024-01-09 08:29 UTC
Labels: bug
