### ISSUE TITLE
Nested Shortcodes

### ISSUE THREAD

**Issue by blindjustis** [thegeeklab/hugo-geekdoc#360] opened 2022-03-02 09:55 UTC
Using geekdoc version 0.27.0
Hugo v0.88.1-5BC54738+extended on windows

Sorry I dont have time to look at this myself ATM - I have worked around it by restructuring the content.
I'm fairly sure it will affect others though,

What I would like to have done was
 
```
{{< tabs "uniqueid" >}}
{{< tab "C#" >}} 
{{< include file="relative/path/from/hugo/root" language="csharp" >}}
{{< /tab >}}
{{< tab "Java" >}} 
{{< include file="relative/path/from/hugo/root" language="java" >}}
{{< /tab >}}
{{< tab "Javascript" >}} 
{{< include file="relative/path/from/hugo/root" language="javascript" >}}
{{< /tab >}}
{{< /tabs >}}
```

**Just using the include shortode for the files without shortcode for the tabs is fine**

Add the tabs and the code no longer renders correctly.
* There is an extra line between the first line of the code and the second line (I think it is caused by the rendering of copy button,  if you look in dark mode the well for the code is split under it)
* It only affects the code; so the line numbers do not line up.
* The tab spacing of the code gets distorted.
* The copy button now only selects the first line of the code.

**I dont know if you want the following raised as a separate issue - but if you wrap an include in an expand, random sections of the highlighted code has the html for the highlighting escaped, so that the html was diplayed not the highlighted code.**

This was for c# and there were no obvious odd characters that triggered the sections that were escaped e.g. the constructor for a class.

**Comment by blindjustis** [comment] 2022-03-02 09:58
Forgot to mention - it is still an issue if you convert the included files to markdown files with code fences around the code - it still has thesame rendering issues.

**Comment by xoxys** [comment] 2022-03-02 10:20
Can you please create a minimal reproducible repo?

**Comment by xoxys** [comment] 2022-03-02 11:22
This seems to be a bug in an older hugo version. Using the latest `hugo v0.93.0-07469082+extended linux/amd64 BuildDate=2022-02-28T08:30:42Z VendorInfo=gohugoio` this looks good to me and the copy button works as expected as well:

![image](https://user-images.githubusercontent.com/3391958/156352139-5419faff-5fa0-4067-b6c1-9c9db654037f.png)

```
{{< tabs "uniqueid" >}}
{{< tab "C#" >}}
{{< include file="static/_includes/code-demo.css" language="csharp" >}}
{{< /tab >}}
{{< tab "Java" >}}
{{< include file="static/_includes/code-demo.css" language="java" >}}
{{< /tab >}}
{{< tab "Javascript" >}}
{{< include file="static/_includes/code-demo.css" language="javascript" >}}
{{< /tab >}}
{{< /tabs >}}
```

**Comment by xoxys** [comment] 2022-03-15 08:46
Closing due to missing feedback.

**Closed by xoxys** 2022-03-15 08:46 UTC
