### ISSUE TITLE
Multiple tables on same page gets shifted columns

### ISSUE THREAD

**Issue by diizzyy** [thegeeklab/hugo-geekdoc#552] opened 2022-12-07 09:06 UTC
Not a huge deal but (2nd) column width seem to increase by each table despite contents having the same width (total width is the same).

How to reproduce:
Create two or more identical tables on the same page containing two columns

Thanks for a great theme!

**Comment by xoxys** [comment] 2022-12-09 12:28
Cant reproduce. Can you please create a minimal example? In the best case, a public accessible git repository.

```Markdown
## Attributes

| Name            | Description                                      |
| --------------- | ------------------------------------------------ |
| size (optional) | size of the first column (small\|regular\|large) |

| Name            | Description                                      |
| --------------- | ------------------------------------------------ |
| size (optional) | size of the first column (small\|regular\|large) |

| Name            | Description                                      |
| --------------- | ------------------------------------------------ |
| size (optional) | size of the first column (small\|regular\|large) |

| Name            | Description                                      |
| --------------- | ------------------------------------------------ |
| size (optional) | size of the first column (small\|regular\|large) |

```

![image](https://user-images.githubusercontent.com/3391958/206702429-13d0932c-8e1d-44da-aa31-32af1d66391d.png)

**Comment by diizzyy** [comment] 2022-12-09 21:02
I found what's causing this issue.
If a table and columns share the same width in markdown the rendered position gets adjusted depending on amount of characters within the first row of cells.

```
| XXXXXX	| FooFooFooFo		|
|---------------|-----------------------|
| XXXXXXXXXX	| 10.0.10.1/24		|
| XXXXXXX	| 10.0.10.243		|
| XXXXXXXXX	| 10.0.10.245		|
| XXXXXX	| 10.0.10.253		|


| XXXXXX	| FooFooFooFo		|
|---------------|-----------------------|
| XXXXXXXXXXX	| 10.0.100.1/24		|
| XXXXXXX	| 10.0.100.90		|
| XXXXXXXXXXX	| 10.0.100.100		|
| XXXXXX	| 10.0.100.240		|
```

I guess that's not adjustable?

**Comment by xoxys** [comment] 2022-12-09 21:23
I would suggest to always use spaces instead of tabs, see https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md010

Besides that, there is as far as I know no way to control table rendering in the theme. This is fully controlled by the hugo markdown renderer. For this reason, I'm going to close this issue.

**Closed by xoxys** 2022-12-09 21:23 UTC
Labels: question
